/*
 * Copyright (c) 2010, 2025, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 *
 */

// Precompiled headers are turned off if the user passes
// --disable-precompiled-headers to configure.

// These header files are included in at least 130 C++ files, as of
// measurements made in August 2025.

#include "asm/register.hpp"
#include "classfile/classLoaderData.hpp"
#include "classfile/javaClasses.hpp"
#include "classfile/systemDictionary.hpp"
#include "classfile/vmClassID.hpp"
#include "classfile/vmClassMacros.hpp"
#include "classfile/vmClasses.hpp"
#include "code/compressedStream.hpp"
#include "code/vmreg.hpp"
#include "code/vmregTypes.hpp"
#include "compiler/compilerDefinitions.hpp"
#include "compiler/compiler_globals_pd.hpp"
#include "compiler/oopMap.hpp"
#include "gc/shared/barrierSetConfig.hpp"
#include "gc/shared/collectedHeap.hpp"
#include "gc/shared/gcCause.hpp"
#include "gc/shared/gcId.hpp"
#include "gc/shared/gcThreadLocalData.hpp"
#include "gc/shared/gcUtil.hpp"
#include "gc/shared/gcWhen.hpp"
#include "gc/shared/softRefPolicy.hpp"
#include "gc/shared/threadLocalAllocBuffer.hpp"
#include "gc/shared/verifyOption.hpp"
#include "interpreter/bytecodes.hpp"
#include "logging/log.hpp"
#include "logging/logDecorators.hpp"
#include "logging/logLevel.hpp"
#include "logging/logOutputList.hpp"
#include "logging/logPrefix.hpp"
#include "logging/logSelection.hpp"
#include "logging/logTag.hpp"
#include "logging/logTagSet.hpp"
#include "memory/allStatic.hpp"
#include "memory/allocation.hpp"
#include "memory/arena.hpp"
#include "memory/iterator.hpp"
#include "memory/memRegion.hpp"
#include "memory/metaspace.hpp"
#include "memory/metaspaceStats.hpp"
#include "memory/padded.hpp"
#include "memory/referenceType.hpp"
#include "memory/reservedSpace.hpp"
#include "memory/resourceArea.hpp"
#include "memory/universe.hpp"
#include "metaprogramming/enableIf.hpp"
#include "metaprogramming/primitiveConversions.hpp"
#include "nmt/allocationSite.hpp"
#include "nmt/arrayWithFreeList.hpp"
#include "nmt/mallocHeader.hpp"
#include "nmt/mallocSiteTable.hpp"
#include "nmt/mallocTracker.hpp"
#include "nmt/memBaseline.hpp"
#include "nmt/memTag.hpp"
#include "nmt/memTracker.hpp"
#include "nmt/memoryFileTracker.hpp"
#include "nmt/nmtCommon.hpp"
#include "nmt/nmtNativeCallStackStorage.hpp"
#include "nmt/nmtTreap.hpp"
#include "nmt/regionsTree.hpp"
#include "nmt/threadStackTracker.hpp"
#include "nmt/virtualMemoryTracker.hpp"
#include "nmt/vmatree.hpp"
#include "oops/accessDecorators.hpp"
#include "oops/annotations.hpp"
#include "oops/array.hpp"
#include "oops/arrayKlass.hpp"
#include "oops/arrayOop.hpp"
#include "oops/compressedKlass.hpp"
#include "oops/constMethod.hpp"
#include "oops/constMethodFlags.hpp"
#include "oops/constantPool.hpp"
#include "oops/cpCache.hpp"
#include "oops/fieldInfo.hpp"
#include "oops/instanceKlass.hpp"
#include "oops/instanceKlassFlags.hpp"
#include "oops/instanceOop.hpp"
#include "oops/klass.hpp"
#include "oops/klassFlags.hpp"
#include "oops/markWord.hpp"
#include "oops/metadata.hpp"
#include "oops/method.hpp"
#include "oops/methodFlags.hpp"
#include "oops/objArrayKlass.hpp"
#include "oops/objArrayOop.hpp"
#include "oops/objLayout.hpp"
#include "oops/oop.hpp"
#include "oops/oopHandle.hpp"
#include "oops/oopsHierarchy.hpp"
#include "oops/stackChunkOop.hpp"
#include "oops/symbol.hpp"
#include "oops/typeArrayKlass.hpp"
#include "oops/typeArrayOop.hpp"
#include "oops/weakHandle.hpp"
#include "runtime/abstract_vm_version.hpp"
#include "runtime/atomic.hpp"
#include "runtime/basicLock.hpp"
#include "runtime/continuation.hpp"
#include "runtime/continuationEntry.hpp"
#include "runtime/flags/flagSetting.hpp"
#include "runtime/frame.hpp"
#include "runtime/globals.hpp"
#include "runtime/globals_shared.hpp"
#include "runtime/handles.hpp"
#include "runtime/handshake.hpp"
#include "runtime/javaFrameAnchor.hpp"
#include "runtime/javaThread.hpp"
#include "runtime/lockStack.hpp"
#include "runtime/monitorChunk.hpp"
#include "runtime/mutex.hpp"
#include "runtime/mutexLocker.hpp"
#include "runtime/orderAccess.hpp"
#include "runtime/os.inline.hpp"
#include "runtime/osInfo.hpp"
#include "runtime/park.hpp"
#include "runtime/perfDataTypes.hpp"
#include "runtime/safepoint.hpp"
#include "runtime/safepointMechanism.hpp"
#include "runtime/semaphore.hpp"
#include "runtime/signature.hpp"
#include "runtime/stackChunkFrameStream.hpp"
#include "runtime/stackOverflow.hpp"
#include "runtime/stackWatermarkKind.hpp"
#include "runtime/stackWatermarkSet.hpp"
#include "runtime/suspendResumeManager.hpp"
#include "runtime/thread.hpp"
#include "runtime/threadHeapSampler.hpp"
#include "runtime/threadIdentifier.hpp"
#include "runtime/threadLocalStorage.hpp"
#include "runtime/threadStatisticalInfo.hpp"
#include "runtime/timer.hpp"
#include "runtime/unhandledOops.hpp"
#include "runtime/vmOperation.hpp"
#include "runtime/vm_version.hpp"
#include "services/memoryUsage.hpp"
#include "utilities/accessFlags.hpp"
#include "utilities/align.hpp"
#include "utilities/autoRestore.hpp"
#include "utilities/bitMap.hpp"
#include "utilities/breakpoint.hpp"
#include "utilities/bytes.hpp"
#include "utilities/byteswap.hpp"
#include "utilities/checkedCast.hpp"
#include "utilities/compilerWarnings.hpp"
#include "utilities/constantTag.hpp"
#include "utilities/copy.hpp"
#include "utilities/count_leading_zeros.hpp"
#include "utilities/count_trailing_zeros.hpp"
#include "utilities/debug.hpp"
#include "utilities/deferredStatic.hpp"
#include "utilities/enumIterator.hpp"
#include "utilities/exceptions.hpp"
#include "utilities/filterQueue.hpp"
#include "utilities/forbiddenFunctions.hpp"
#include "utilities/formatBuffer.hpp"
#include "utilities/globalDefinitions.hpp"
#include "utilities/growableArray.hpp"
#include "utilities/linkedlist.hpp"
#include "utilities/macros.hpp"
#include "utilities/nativeCallStack.hpp"
#include "utilities/numberSeq.hpp"
#include "utilities/ostream.hpp"
#include "utilities/population_count.hpp"
#include "utilities/powerOfTwo.hpp"
#include "utilities/resourceHash.hpp"
#include "utilities/sizes.hpp"
#include "utilities/tableStatistics.hpp"
#include "utilities/ticks.hpp"
#include "utilities/unsigned5.hpp"
#include "utilities/utf8.hpp"
#include "utilities/vmEnums.hpp"
#include "utilities/waitBarrier.hpp"
#include "utilities/waitBarrier_generic.hpp"

#ifdef COMPILER2
#include "asm/assembler.hpp"
#include "asm/codeBuffer.hpp"
#include "cds/cds_globals.hpp"
#include "classfile/vmIntrinsics.hpp"
#include "code/codeBlob.hpp"
#include "code/debugInfo.hpp"
#include "code/location.hpp"
#include "code/nmethod.hpp"
#include "code/oopRecorder.hpp"
#include "code/pcDesc.hpp"
#include "code/relocInfo.hpp"
#include "compiler/compiler_globals.hpp"
#include "jfr/support/jfrIntrinsics.hpp"
#include "logging/logDecorations.hpp"
#include "logging/logHandle.hpp"
#include "logging/logMessage.hpp"
#include "logging/logMessageBuffer.hpp"
#include "logging/logStream.hpp"
#include "opto/adlcVMDeps.hpp"
#include "opto/c2_globals.hpp"
#include "runtime/nonJavaThread.hpp"
#include "runtime/stubDeclarations.hpp"
#include "runtime/stubInfo.hpp"
#include "utilities/resizeableResourceHash.hpp"
#endif

#if INCLUDE_JFR
#include "asm/assembler.hpp"
#include "asm/codeBuffer.hpp"
#include "cds/cds_globals.hpp"
#include "classfile/vmIntrinsics.hpp"
#include "code/codeBlob.hpp"
#include "code/nmethod.hpp"
#include "code/oopRecorder.hpp"
#include "code/pcDesc.hpp"
#include "code/relocInfo.hpp"
#include "code/vmreg.inline.hpp"
#include "compiler/compiler_globals.hpp"
#include "gc/epsilon/epsilon_globals.hpp"
#include "gc/shared/gc_globals.hpp"
#include "jfr/jfr.hpp"
#include "jfr/periodic/sampling/jfrCPUTimeThreadSampler.hpp"
#include "jfr/periodic/sampling/jfrSampleRequest.hpp"
#include "jfr/recorder/checkpoint/types/traceid/jfrTraceId.hpp"
#include "jfr/recorder/checkpoint/types/traceid/jfrTraceIdMacros.hpp"
#include "jfr/recorder/storage/jfrBuffer.hpp"
#include "jfr/support/jfrIntrinsics.hpp"
#include "jfr/support/jfrKlassExtension.hpp"
#include "jfr/support/jfrThreadExtension.hpp"
#include "jfr/support/jfrThreadId.hpp"
#include "jfr/support/jfrThreadLocal.hpp"
#include "jfr/support/jfrTraceIdExtension.hpp"
#include "jfr/utilities/jfrAllocation.hpp"
#include "jfr/utilities/jfrBlob.hpp"
#include "jfr/utilities/jfrRefCountPointer.hpp"
#include "jfr/utilities/jfrTime.hpp"
#include "jfr/utilities/jfrTypes.hpp"
#include "logging/logDecorations.hpp"
#include "logging/logHandle.hpp"
#include "logging/logMessage.hpp"
#include "logging/logMessageBuffer.hpp"
#include "logging/logStream.hpp"
#include "runtime/nonJavaThread.hpp"
#include "runtime/stubDeclarations.hpp"
#include "runtime/stubInfo.hpp"
#include "utilities/resizeableResourceHash.hpp"
#endif

#if INCLUDE_G1GC
#include "asm/codeBuffer.hpp"
#include "code/oopRecorder.hpp"
#include "code/relocInfo.hpp"
#include "compiler/compiler_globals.hpp"
#include "logging/logDecorations.hpp"
#include "logging/logMessageBuffer.hpp"
#include "utilities/resizeableResourceHash.hpp"
#endif

#if INCLUDE_SHENANDOAHGC
#include "asm/codeBuffer.hpp"
#include "code/codeBlob.hpp"
#include "code/oopRecorder.hpp"
#include "code/relocInfo.hpp"
#include "compiler/compiler_globals.hpp"
#include "logging/logDecorations.hpp"
#include "logging/logHandle.hpp"
#include "logging/logMessage.hpp"
#include "logging/logMessageBuffer.hpp"
#include "logging/logStream.hpp"
#include "utilities/resizeableResourceHash.hpp"
#endif

#if INCLUDE_ZGC
#include "compiler/compiler_globals.hpp"
#endif
